query Geojson(
  $typeIds: [TypeId!]
  $domaineIds: [DomaineId]
  $statutIds: [StatutId!]
  $polices: [Boolean!]
) {
  geojsonMultiPolygons(
    typeIds: $typeIds
    domaineIds: $domaineIds
    statutIds: $statutIds
    polices: $polices
  ) {
    type
    features {
      type
      properties {
        nom
        police
        type {
          id
          nom
        }
        domaine {
          id
          nom
        }
        statut {
          id
          nom
        }
        phases {
          id
          type {
            nom
          }
          emprise {
            id
            nom
          }
          date
          duree
        }
        substancesPrincipales {
          ...sub
        }
        substancesConnexes {
          ...sub
        }
      }
      geometry {
        type
        coordinates
      }
    }
  }
}

fragment sub on Substance {
  id
  nom
  domaine
  type
  usage
  symbole
  alias
  gerep
  description
  legal {
    id
    nom
    description
    lien
  }
}
