query Titres(
  $typeIds: [ID!]
  $domaineIds: [ID!]
  $statutIds: [ID!]
  $substances: [String!]
  $noms: [String!]
) {
  titres(
    typeIds: $typeIds
    domaineIds: $domaineIds
    statutIds: $statutIds
    substances: $substances
    noms: $noms
  ) {
    ...titre
  }
}

fragment titre on Titre {
  id
  nom
  type {
    id
    type {
      nom
    }
  }
  domaine {
    id
    nom
  }
  statut {
    id
    nom
  }
  references {
    ...reference
  }
  dateDebut
  dateFin
  dateDemande
  volume
  surface
  volumeUnite {
    nom
  }
  substances {
    ...substance
  }
  administrations {
    ...administration
  }
  titulaires {
    ...entreprise
  }
  amodiataires {
    ...entreprise
  }
  geojsonPoints {
    ...geojsonPoints
  }
  geojsonMultiPolygon {
    ...geojsonMultiPolygon
  }
  pays {
    id
    nom
    regions {
      id
      nom
      departements {
        id
        nom
        communes {
          id
          nom
        }
      }
    }
  }
}

fragment administration on Administration {
  nom
}

fragment entreprise on Entreprise {
  etablissements {
    nom
    dateDebut
  }
  nom
  legalSiren
  legalEtranger
}

fragment geojsonMultiPolygon on GeojsonMultiPolygon {
  type
  properties {
    etapeId
  }
  geometry {
    type
    coordinates
  }
}

fragment geojsonPoints on GeojsonPoints {
  type
  properties {
    etapeId
  }
  features {
    type
    properties {
      groupe
      contour
      point
      nom
      description
    }
    geometry {
      type
      coordinates
    }
  }
}

fragment substance on TitreSubstance {
  nom
  connexe
  gerep
  description
  legales {
    nom
  }
}

fragment reference on Reference {
  type {
    id
    nom
  }
  nom
}
